chat/urls/urls.py
from django.urls import path
from chat.views import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('inbox/<str:room_uuid>', views.inbox, name='inbox'),
]

core/urls/urls.py
from django.urls import path
from core.views import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

dashboard/urls/urls.py
from django.urls import path
from dashboard.views import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('be-an-instructor/', views.be_an_instructor, name='be_an_instructor'),
]

pattho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('saasowner/', include('saasowner.urls.urls')),
    path('', include('core.urls.urls')),
    path('user/', include('user.urls.urls')),
    path('dashboard/', include('dashboard.urls.urls')),
    # path('student/', include('student.urls.urls')),
    path('instructor/', include('instructor.urls.urls')),
    path('chat/', include('chat.urls.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saasowner/urls/urls.py
from django.urls import path, include
from saasowner.views import views

app_name = 'saasowner'

urlpatterns = [
    path('', views.index, name='index'),
    path('users/' , include('saasowner.urls.user_urls')),
]

user/urls/urls.py
from django.urls import path, include
from user.views import views

app_name = 'user'

urlpatterns = [
    # api urls
    path('api/', include('user.urls.api_urls')),

    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

core/views/views.py
from django.shortcuts import render



def index(request):
    return render(request, 'core/index/index.html')

core/templates/app.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %} | Pattho</title>

    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.min.css"
      rel="stylesheet"
    />

    {% block css %} {% endblock css %}
  </head>
  <body>
    {% include 'header.html' %}
    <main>{% block content %} {% endblock content %}</main>
    {% include 'footer.html' %}

    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.umd.min.js"
    ></script>

    {% block js %} {% endblock js %}
  </body>
</html>

core/templates/header.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
    <!-- Container wrapper -->
    <div class="container">
      <!-- Navbar brand -->
      <a class="navbar-brand me-2" href="{% url 'core:index' %}">
        Pattho
      </a>
  
      <!-- Toggle button -->
      <button
        data-mdb-collapse-init
        class="navbar-toggler"
        type="button"
        data-mdb-target="#navbarButtonsExample"
        aria-controls="navbarButtonsExample"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarButtonsExample">
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'chat:index' %}">Message</a>
          </li>
          {% endif %}
        </ul>
        <!-- Left links -->
  
        {% if not user.is_authenticated %}
        <div class="d-flex align-items-center">
          <a href="{% url 'user:login' %}" data-mdb-ripple-init type="button" class="btn btn-primary px-3 me-2">
            Login
          </a>
          <a href="#" data-mdb-ripple-init type="button" class="btn btn-primary me-3">
            Register
          </a>
        </div>
        {% else %}
        <a data-mdb-dropdown-init class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" href="#"
        id="navbarDropdownMenuLink" role="button" aria-expanded="false">
        <img src="https://mdbootstrap.com/img/new/avatars/2.jpg" class="rounded-circle" height="22" alt="Avatar"
          loading="lazy" />
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
          {% if user.is_superuser %}
          <li><a class="dropdown-item" href="{% url 'saasowner:index' %}">Admin Panel</a></li>
          {% endif %}

          {% if user.is_authenticated %}
          <li><a class="dropdown-item" href="{% url 'dashboard:index' %}">Dashboard</a></li>
          {% endif %}
          <!-- <li><a class="dropdown-item" href="#">Settings</a></li> -->
          <li>
            <form action="{% url 'user:logout' %}" method="post">
              {% csrf_token %}
              <button class="dropdown-item">Logout</button>
            </form>
          </li>
        </ul>
        {% endif %}
      </div>
      <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
     
  </nav>
  <!-- Navbar -->