dashboard/urls/urls.py
from django.urls import path
from dashboard.views import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('be-an-instructor/', views.be_an_instructor, name='be_an_instructor'),
]

instructor/urls/urls.py
from django.urls import path, include
from instructor.views import views

app_name = 'instructor'

urlpatterns = [
    path('u/', include('instructor.urls.update_urls')),

    path('become-an-instructor/', views.become_an_instructor, name='become_an_instructor'),
]

pattho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('saasowner/', include('saasowner.urls.urls')),
    path('', include('core.urls.urls')),
    path('user/', include('user.urls.urls')),
    path('dashboard/', include('dashboard.urls.urls')),
    # path('student/', include('student.urls.urls')),
    path('instructor/', include('instructor.urls.urls')),
    path('chat/', include('chat.urls.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from course import models as course_models

@login_required
def index(request):
    return render(request, 'dashboard/index/index.html')

@login_required
def be_an_instructor(request):
    course_categories = course_models.CourseCategory.objects.all()
    context = {
        'course_categories': course_categories,
    }
    return render(request, 'dashboard/be_an_instructor/index.html', context)

dashboard/templates/dashboard/be_an_instructor/index.html
{% extends 'dashboard/app.html' %} 

{% block content %}

<section class="container">
  {% include 'components/messages.html' %} 
  <div id="success_message" class="d-none"></div>
  <div id="error_message" class="d-none"></div>
  
  {% if not user.is_instructor %}
  <h1 class="text-center my-3">Be an Instructor</h1>

  <div class="row d-flex justify-content-center">
    <div class="col-8">
      <div class="text-center border border-1 p-3">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam,
          voluptatibus. Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Quisquam, voluptatibus.
        </p>
        <form
          action="{% url 'instructor:become_an_instructor' %}"
          method="post"
        >
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">
            Become an Instructor
          </button>
        </form>
      </div>
    </div>
  </div>
  {% else %}
  <div class="row my-3">
    <div class="col-12">
      <h3 class="text-center my-3">Select your category</h3>
    </div>

    {% for category in course_categories %}
    <div class="col-12 col-md-3 mb-2">
      <div class="border border-1 p-3 h-100 w-100">
        <div class="form-check">
          <input
            class="form-check-input"
            type="checkbox"
            value=""
            id="category-{{category.id}}"
            {% if category in user.instructor.categories.all %}checked{% endif %}
          />
          <label class="form-check-label" for="category-{{category.id}}">
            {{category.name}}
          </label>
        </div>
      </div>
    </div>
    {% endfor %}
    <div class="text-center">
      <button id="category-submit-button" type="submit" class="btn btn-success">
        Submit
      </button>
    </div>
  </div>
  {% endif %}
</section>

{% endblock content %} 

{% block js %}

<script>
  const updateCategories = () => {
    const successMessage = document.getElementById("success_message");
    const errorMessage = document.getElementById("error_message");

    const categories = [];
    const csrfmiddlewaretoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
    const categoryInputs = document.querySelectorAll('input[type="checkbox"]');
    categoryInputs.forEach((input) => {
      if (input.checked) {
        categories.push(input.id.split("-")[1]);
      }
    });

    fetch("{% url 'instructor:update:update_instructor_category' %}", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": csrfmiddlewaretoken,
      },
      body: JSON.stringify({
        categories: categories,
      }),
    })
      .then((response) => response.json())
      .then((data) => {
        // console.log(data);
        if (data.status === "success") {
          successMessage.innerHTML = data.html;
          successMessage.classList.remove("d-none");

        } else {
          errorMessage.innerHTML = data.html;
          errorMessage.classList.remove("d-none");
        }
      })
      .catch((error) => {
        // console.error(error);
      })
      .finally(() => {
        // console.log("Request completed");
      });
  };



  document.querySelector("#category-submit-button").addEventListener("click", () => {
    updateCategories();
  });
</script>

{% endblock js %}