core/urls/urls.py
from django.urls import path
from core.views import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

dashboard/urls/urls.py
from django.urls import path
from dashboard.views import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('be-an-instructor/', views.be_an_instructor, name='be_an_instructor'),
]

pattho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('saasowner/', include('saasowner.urls.urls')),
    path('', include('core.urls.urls')),
    path('user/', include('user.urls.urls')),
    path('dashboard/', include('dashboard.urls.urls')),
    # path('student/', include('student.urls.urls')),
    path('instructor/', include('instructor.urls.urls')),
    path('chat/', include('chat.urls.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls/urls.py
from django.urls import path, include
from user.views import views

app_name = 'user'

urlpatterns = [
    # api urls
    path('api/', include('user.urls.api_urls')),

    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from course import models as course_models

@login_required
def index(request):
    return render(request, 'dashboard/index/index.html')

@login_required
def be_an_instructor(request):
    course_categories = course_models.CourseCategory.objects.all()
    context = {
        'course_categories': course_categories,
    }
    return render(request, 'dashboard/be_an_instructor/index.html', context)

dashboard/templates/dashboard/app.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block title %}{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'theme/user/assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'theme/user/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'theme/user/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'theme/user/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'theme/user/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'theme/user/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'theme/user/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'theme/user/assets/css/main.css' %}" rel="stylesheet">

  {% block css %} {% endblock css %}

</head>

<body class="index-page">

  {% include 'dashboard/header.html' %}
  {% csrf_token %}
  <main class="main" style="min-height: 80vh;">
    {% block content %} {% endblock content %}
  </main>

  <footer id="footer" class="footer position-relative light-background">

    <div class="container">
      <div class="copyright text-center ">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">Pattho</strong> <span>All Rights Reserved</span></p>
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'theme/user/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/typed.js/typed.umd.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'theme/user/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'theme/user/assets/js/main.js' %}"></script>

  {% block js %} {% endblock js %}

</body>

</html>

dashboard/templates/dashboard/header.html
{% load static %}

<header id="header" class="header dark-background d-flex flex-column">
    <i class="header-toggle d-xl-none bi bi-list"></i>

    <div class="profile-img">
      <img src="{{user.user_image_url}}" alt="" class="img-fluid rounded-circle">
    </div>

    <a href="index.html" class="logo d-flex align-items-center justify-content-center">
      <!-- Uncomment the line below if you also wish to use an image logo -->
      <!-- <img src="assets/img/logo.png" alt=""> -->
      <h1 class="sitename">{{user.full_name}}</h1>
    </a>

    <!-- <div class="social-links text-center">
      <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
      <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
      <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
      <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
      <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
    </div> -->

    <nav id="navmenu" class="navmenu">
      <ul>
         <li>
          <!-- class="active" -->
          <a href="{% url 'core:index' %}"><i class="bi bi-house navicon"></i>Go Back To Site</a>
        </li>
        <li>
          <a href="{% url 'dashboard:index' %}"><i class="bi bi-speedometer2 navicon"></i>Dashboard</a>
        </li>
        <li>
          <a href="{% url 'dashboard:be_an_instructor' %}"><i class="bi bi-x-diamond-fill navicon"></i> Be An Instructor</a>
        </li>
        <li>
          <form action="{% url 'user:logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger"><i class="bi bi-box-arrow-right navicon"> </i>Logout</button>
          </form>
        </li>
        <!-- <li><a href="#resume"><i class="bi bi-file-earmark-text navicon"></i> Resume</a></li> -->
        <!-- <li><a href="#portfolio"><i class="bi bi-images navicon"></i> Portfolio</a></li> -->
        <!-- <li><a href="#services"><i class="bi bi-hdd-stack navicon"></i> Services</a></li> -->
        <!-- <li class="dropdown"><a href="#"><i class="bi bi-menu-button navicon"></i> <span>Dropdown</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
          <ul>
            <li><a href="#">Dropdown 1</a></li>
            <li class="dropdown"><a href="#"><span>Deep Dropdown</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
              <ul>
                <li><a href="#">Deep Dropdown 1</a></li>
                <li><a href="#">Deep Dropdown 2</a></li>
                <li><a href="#">Deep Dropdown 3</a></li>
                <li><a href="#">Deep Dropdown 4</a></li>
                <li><a href="#">Deep Dropdown 5</a></li>
              </ul>
            </li>
            <li><a href="#">Dropdown 2</a></li>
            <li><a href="#">Dropdown 3</a></li>
            <li><a href="#">Dropdown 4</a></li>
          </ul>
        </li> -->
        <!-- <li><a href="#contact"><i class="bi bi-envelope navicon"></i> Contact</a></li> -->
      </ul>
    </nav>

  </header>